# Generated by Django 3.0.7 on 2020-10-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
        migrations.AddField(
            model_name='category',
            name='photos',
            field=models.ManyToManyField(to='core.Photo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='noimage.png', upload_to='images/'),
        ),
    ]
