# Generated by Django 3.0.7 on 2020-10-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201020_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='location',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(default='no description', max_length=500),
        ),
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
    ]
