# Generated by Django 3.0.7 on 2020-10-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201026_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='category',
            new_name='profile',
        ),
    ]
